model_list:
  - model_name: llama3-70b-groq
    litellm_params:
      model: groq/llama3-70b-8192
      api_base: https://api.groq.com/openai/v1
      api_key: os.environ/GROQ_API_KEY
  
  - model_name: llama3-8b-togetherai
    litellm_params:
      model: together_ai/meta-llama/Llama-3-8b-chat-hf
      api_base: https://api.together.xyz/v1
      api_key: os.environ/TOGETHERAI_API_KEY
  
  - model_name: llama3-70b-togetherai
    litellm_params:
      model: together_ai/meta-llama/Llama-3-70b-chat-hf
      api_base: https://api.together.xyz/v1
      api_key: os.environ/TOGETHERAI_API_KEY
  
  - model_name: llama-3-70b-tgi
    litellm_params:
        model: openai/meta-llama/Meta-Llama-3-70B-Instruct
        api_base: http://host.docker.internal:8080/v1
        api_key: "_"

  - model_name: llama-3-8b-tgi
    litellm_params:
        model: openai/meta-llama/Meta-Llama-3-8B-Instruct
        api_base: http://host.docker.internal:8081/v1
        api_key: "_"
  
  - model_name: llama-3-8b-sft-tgi
    litellm_params:
        model: openai/meta-llama/Meta-Llama-3-8B-Instruct
        api_base: http://host.docker.internal:8082/v1
        api_key: "_"
  
  - model_name: '*'
    litellm_params:
      model: openai/*
      api_key: os.environ/OPENAI_API_KEY
  

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: True
  set_verbose: True
  # cache: True
  # cache_params:
  #   type: "redis"